export const SIGN_DATA = {
  Aries: {
    sanskrit: 'Mesha',
    symbol: '♈',
    hindi: 'मेष',
    element: 'Fire',
    quality: 'Movable (Chara)',
    ruler: 'Mars',
    exalted: 'Sun',
    debilitated: 'Saturn',
    description:
      'Mesha champions new beginnings with Mars-fueled determination. This fiery sign thrives on pioneering action, values self-assertion, and seeks to forge ahead even when the path is uncharted, echoing the warrior energy described in Vedic rishis.',
    traits: ['Courageous', 'Energetic', 'Independent'],
  },
  Taurus: {
    sanskrit: 'Vrishabha',
    symbol: '♉',
    hindi: 'वृषभ',
    element: 'Earth',
    quality: 'Fixed (Sthira)',
    ruler: 'Venus',
    exalted: 'Moon',
    debilitated: 'Mars',
    description:
      'Vrishabha represents stability, cultivating beauty and abundance through Venusian refinement. As a fixed earth sign it safeguards material comforts, rewards patience, and prefers tangible results, grounding the chart like a steady bull of the nakshatras.',
    traits: ['Patient', 'Sensual', 'Reliable'],
  },
  Gemini: {
    sanskrit: 'Mithuna',
    symbol: '♊',
    hindi: 'मिथुन',
    element: 'Air',
    quality: 'Dual (Dvisvabhava)',
    ruler: 'Mercury',
    exalted: 'None',
    debilitated: 'None',
    description:
      'Mithuna is the messenger sign of Mercury, weaving intelligence and conversation across the skies. It splits its focus elegantly between dual perspectives, learning quickly and translating celestial messages into nimble choices.',
    traits: ['Curious', 'Communicative', 'Adaptable'],
  },
  Cancer: {
    sanskrit: 'Karka',
    symbol: '♋',
    hindi: 'कर्क',
    element: 'Water',
    quality: 'Movable (Chara)',
    ruler: 'Moon',
    exalted: 'Jupiter',
    debilitated: 'Saturn',
    description:
      'Karka embodies the Moon’s sensitive waters, holding the emotional blueprint of family and home. This nurturing sign senses tides, interprets samskaras, and will protect their inner circle with lunar patience.',
    traits: ['Nurturing', 'Intuitive', 'Protective'],
  },
  Leo: {
    sanskrit: 'Simha',
    symbol: '♌',
    hindi: 'सिंह',
    element: 'Fire',
    quality: 'Fixed (Sthira)',
    ruler: 'Sun',
    exalted: 'None',
    debilitated: 'None',
    description:
      'Simha shines with regal Sun energy, wielding creativity and leadership in dharma-like service. This proud fire sign commands respect while using personal radiance to inspire collective purpose.',
    traits: ['Confident', 'Generous', 'Dramatic'],
  },
  Virgo: {
    sanskrit: 'Kanya',
    symbol: '♍',
    hindi: 'कन्या',
    element: 'Earth',
    quality: 'Mutable (Dvimushthita)',
    ruler: 'Mercury',
    exalted: 'Mercury',
    debilitated: 'Venus',
    description:
      'Kanya is the analytical servant that Mercury empowers to purify details and serve society. Through methodical observation, this earth sign refines processes, seeks perfection, and honors sacred duty by tending to the small yet meaningful elements of life.',
    traits: ['Analytical', 'Practical', 'Diligent'],
  },
  Libra: {
    sanskrit: 'Tula',
    symbol: '♎',
    hindi: 'तुला',
    element: 'Air',
    quality: 'Movable (Chara)',
    ruler: 'Venus',
    exalted: 'Saturn',
    debilitated: 'Moon',
    description:
      'Tula carries the balance beam of Venus and fosters harmony in relationships and justice. Airy and diplomatic, it seeks beauty, partnership, and fairness while navigating conflicting energies with grace.',
    traits: ['Diplomatic', 'Fair-minded', 'Charming'],
  },
  Scorpio: {
    sanskrit: 'Vrishchika',
    symbol: '♏',
    hindi: 'वृश्चिक',
    element: 'Water',
    quality: 'Fixed (Sthira)',
    ruler: 'Mars',
    exalted: 'None',
    debilitated: 'None',
    description:
      'Vrishchika channels intense transformational power, often dipping into hidden currents to awaken soul-consciousness. Under Mars’ influence this water sign pursues depth, embraces kriya, and refuses to settle for surface-level meaning.',
    traits: ['Passionate', 'Resourceful', 'Secretive'],
  },
  Sagittarius: {
    sanskrit: 'Dhanu',
    symbol: '♐',
    hindi: 'धनु',
    element: 'Fire',
    quality: 'Mutable (Dvimushthita)',
    ruler: 'Jupiter',
    exalted: 'None',
    debilitated: 'None',
    description:
      'Dhanu is the philosophical archer guided by Jupiter, forever seeking higher learning, pilgrimage, and moral clarity. This expansive fire sign wants to translate Vedic wisdom into lived adventure and bless others with optimism.',
    traits: ['Optimistic', 'Philosophical', 'Adventurous'],
  },
  Capricorn: {
    sanskrit: 'Makara',
    symbol: '♑',
    hindi: 'मकर',
    element: 'Earth',
    quality: 'Movable (Chara)',
    ruler: 'Saturn',
    exalted: 'Mars',
    debilitated: 'Moon',
    description:
      'Makara embodies disciplined ambition, honoring Saturn’s vow to uphold tradition and structure. This mountain-goat sign climbs patiently, builds enduring foundations, and keeps dharma in view even when outcomes lag.',
    traits: ['Disciplined', 'Responsible', 'Strategic'],
  },
  Aquarius: {
    sanskrit: 'Kumbha',
    symbol: '♒',
    hindi: 'कुम्भ',
    element: 'Air',
    quality: 'Fixed (Sthira)',
    ruler: 'Saturn',
    exalted: 'Venus',
    debilitated: 'Mars',
    description:
      'Kumbha channels Saturnian detachment to reform systems for collective liberation. This visionary air sign feels the pressure of karma, yet keeps a humanitarian outlook, valuing innovative ideas over tradition.',
    traits: ['Humanitarian', 'Innovative', 'Objective'],
  },
  Pisces: {
    sanskrit: 'Meena',
    symbol: '♓',
    hindi: 'मीन',
    element: 'Water',
    quality: 'Mutable (Dvimushthita)',
    ruler: 'Jupiter',
    exalted: 'Mercury',
    debilitated: 'Venus',
    description:
      'Meena flows with dreamlike compassion, offering deep psychic attunement and devotion. As a mutable water sign, it merges with the cosmos, absorbs subtle currents, and seeks to heal through empathy.',
    traits: ['Compassionate', 'Intuitive', 'Devotional'],
  },
};
