export const NAKSHATRA_DATA = {
  Ashwini: {
    number: 1,
    sanskrit: 'अश्विनी',
    span: { start: 0, end: 13.333 },
    sign: 'Aries',
    ruler: 'Ketu',
    deity: 'Ashwini Kumaras',
    symbol: 'Horse head',
    gana: 'Deva',
    sounds: ['Chu', 'Che', 'Cho', 'La'],
    description: 'The first nakshatra represents new beginnings, healing, and swift action. Associated with the divine physicians of the gods.',
  },
  Bharani: {
    number: 2,
    sanskrit: 'भरणी',
    span: { start: 13.333, end: 26.667 },
    sign: 'Aries',
    ruler: 'Venus',
    deity: 'Yama',
    symbol: 'Yoni',
    gana: 'Manushya',
    sounds: ['Lee', 'Lu', 'Le', 'Lo'],
    description: 'Represents creation, transformation, and the cycle of birth and death. Connected to the god of death and justice.',
  },
  Krittika: {
    number: 3,
    sanskrit: 'कृत्तिका',
    span: { start: 26.667, end: 40 },
    sign: 'Aries/Taurus',
    ruler: 'Sun',
    deity: 'Agni',
    symbol: 'Knife or Flame',
    gana: 'Rakshasa',
    sounds: ['A', 'I', 'U', 'E'],
    description: 'The cutting star associated with fire, purification, and the Pleiades. Represents the power of transformation through fire.',
  },
  Rohini: {
    number: 4,
    sanskrit: 'रोहिणी',
    span: { start: 40, end: 53.333 },
    sign: 'Taurus',
    ruler: 'Moon',
    deity: 'Brahma',
    symbol: 'Cart or Chariot',
    gana: 'Manushya',
    sounds: ['O', 'Ba', 'Bi', 'Bu'],
    description: 'The red one, associated with growth, fertility, and abundance. Connected to the creator god Brahma.',
  },
  Mrigashira: {
    number: 5,
    sanskrit: 'मृगशीर्ष',
    span: { start: 53.333, end: 66.667 },
    sign: 'Taurus',
    ruler: 'Mars',
    deity: 'Soma',
    symbol: 'Deer\'s head',
    gana: 'Deva',
    sounds: ['Ve', 'Vo', 'Ka', 'Ki'],
    description: 'The deer\'s head, representing search, quest, and the moon\'s healing powers. Associated with seeking and exploration.',
  },
  Ardra: {
    number: 6,
    sanskrit: 'आर्द्रा',
    span: { start: 66.667, end: 80 },
    sign: 'Gemini',
    ruler: 'Rahu',
    deity: 'Rudra',
    symbol: 'Teardrop',
    gana: 'Manushya',
    sounds: ['Ku', 'Gha', 'Ng', 'Chha'],
    description: 'The moist one, associated with storms, transformation, and the destructive aspect of Shiva. Represents turbulent change.',
  },
  Punarvasu: {
    number: 7,
    sanskrit: 'पुनर्वसु',
    span: { start: 80, end: 93.333 },
    sign: 'Gemini',
    ruler: 'Jupiter',
    deity: 'Aditi',
    symbol: 'Bow and quiver',
    gana: 'Deva',
    sounds: ['Ke', 'Ko', 'Ha', 'Hi'],
    description: 'The return of the light, associated with renewal, prosperity, and the mother goddess Aditi.',
  },
  Pushya: {
    number: 8,
    sanskrit: 'पुष्य',
    span: { start: 93.333, end: 106.667 },
    sign: 'Cancer',
    ruler: 'Saturn',
    deity: 'Brihaspati',
    symbol: 'Flower, circle of flowers',
    gana: 'Deva',
    sounds: ['Hu', 'He', 'Ho', 'Da'],
    description: 'The nourisher, associated with nourishment, growth, and spiritual wisdom. Connected to the guru of the gods.',
  },
  Ashlesha: {
    number: 9,
    sanskrit: 'आश्लेषा',
    span: { start: 106.667, end: 120 },
    sign: 'Cancer',
    ruler: 'Mercury',
    deity: 'Nagas',
    symbol: 'Serpent',
    gana: 'Rakshasa',
    sounds: ['Di', 'Du', 'De', 'Do'],
    description: 'The embrace, associated with kundalini energy, transformation, and mystical experiences. Connected to the serpent deities.',
  },
  Magha: {
    number: 10,
    sanskrit: 'मघा',
    span: { start: 120, end: 133.333 },
    sign: 'Leo',
    ruler: 'Ketu',
    deity: 'Pitris',
    symbol: 'Royal Throne',
    gana: 'Rakshasa',
    sounds: ['Ma', 'Mi', 'Mu', 'Me'],
    description: 'The mighty one, associated with power, authority, and ancestral wisdom. Connected to the ancestors and royal dignity.',
  },
  'Purva Phalguni': {
    number: 11,
    sanskrit: 'पूर्व फाल्गुनी',
    span: { start: 133.333, end: 146.667 },
    sign: 'Leo',
    ruler: 'Venus',
    deity: 'Bhaga',
    symbol: 'Front legs of bed',
    gana: 'Manushya',
    sounds: ['Mo', 'Ta', 'Ti', 'Tu'],
    description: 'The former reddish one, associated with love, marriage, and prosperity. Connected to the god of fortune.',
  },
  'Uttara Phalguni': {
    number: 12,
    sanskrit: 'उत्तर फाल्गुनी',
    span: { start: 146.667, end: 160 },
    sign: 'Leo/Virgo',
    ruler: 'Sun',
    deity: 'Aryaman',
    symbol: 'Rear legs of bed',
    gana: 'Manushya',
    sounds: ['Te', 'To', 'Pa', 'Pi'],
    description: 'The latter reddish one, associated with friendship, patronage, and favor. Connected to the god of nobility.',
  },
  Hasta: {
    number: 13,
    sanskrit: 'हस्त',
    span: { start: 160, end: 173.333 },
    sign: 'Virgo',
    ruler: 'Moon',
    deity: 'Savitar',
    symbol: 'Hand',
    gana: 'Deva',
    sounds: ['Pu', 'Sha', 'Na', 'Tha'],
    description: 'The hand, associated with skill, craftsmanship, and healing. Connected to the sun god and creative energy.',
  },
  Chitra: {
    number: 14,
    sanskrit: 'चित्रा',
    span: { start: 173.333, end: 186.667 },
    sign: 'Virgo',
    ruler: 'Mars',
    deity: 'Vishwakarma',
    symbol: 'Pearl',
    gana: 'Rakshasa',
    sounds: ['Pe', 'Po', 'Ra', 'Ri'],
    description: 'The brilliant one, associated with art, beauty, and craftsmanship. Connected to the divine architect.',
  },
  Swati: {
    number: 15,
    sanskrit: 'स्वाती',
    span: { start: 186.667, end: 200 },
    sign: 'Libra',
    ruler: 'Rahu',
    deity: 'Vayu',
    symbol: 'Coral',
    gana: 'Deva',
    sounds: ['Ru', 'Re', 'Ro', 'Ta'],
    description: 'The sword, associated with independence, balance, and the wind god. Represents self-reliance and harmony.',
  },
  Vishakha: {
    number: 16,
    sanskrit: 'विशाखा',
    span: { start: 200, end: 213.333 },
    sign: 'Libra',
    ruler: 'Jupiter',
    deity: 'Indra & Agni',
    symbol: 'Triumphal arch',
    gana: 'Rakshasa',
    sounds: ['Ti', 'Tu', 'Te', 'To'],
    description: 'The forked branch, associated with achievement, leadership, and divine purpose. Connected to Indra and Agni.',
  },
  Anuradha: {
    number: 17,
    sanskrit: 'अनुराधा',
    span: { start: 213.333, end: 226.667 },
    sign: 'Scorpio',
    ruler: 'Saturn',
    deity: 'Mitra',
    symbol: 'Lotus',
    gana: 'Deva',
    sounds: ['Na', 'Ni', 'Nu', 'Ne'],
    description: 'Following Radha, associated with friendship, devotion, and success. Connected to the god of friendship.',
  },
  Jyeshtha: {
    number: 18,
    sanskrit: 'ज्येष्ठा',
    span: { start: 226.667, end: 240 },
    sign: 'Scorpio',
    ruler: 'Mercury',
    deity: 'Indra',
    symbol: 'Earring',
    gana: 'Rakshasa',
    sounds: ['No', 'Ya', 'Yi', 'Yu'],
    description: 'The eldest, associated with seniority, power, and protection. Connected to the king of the gods.',
  },
  Mula: {
    number: 19,
    sanskrit: 'मूल',
    span: { start: 240, end: 253.333 },
    sign: 'Sagittarius',
    ruler: 'Ketu',
    deity: 'Nirriti',
    symbol: 'Bunch of roots',
    gana: 'Rakshasa',
    sounds: ['Ye', 'Yo', 'Ba', 'Bi'],
    description: 'The root, associated with destruction of the old, research, and spiritual liberation. Connected to the goddess of dissolution.',
  },
  'Purva Ashadha': {
    number: 20,
    sanskrit: 'पूर्वाषाढा',
    span: { start: 253.333, end: 266.667 },
    sign: 'Sagittarius',
    ruler: 'Venus',
    deity: 'Apas',
    symbol: 'Elephant tusk',
    gana: 'Manushya',
    sounds: ['Bu', 'Dha', 'Bha', 'Dha'],
    description: 'The former invincible one, associated with victory, spiritual practice, and the waters. Connected to the water deities.',
  },
  'Uttara Ashadha': {
    number: 21,
    sanskrit: 'उत्तराषाढा',
    span: { start: 266.667, end: 280 },
    sign: 'Sagittarius/Capricorn',
    ruler: 'Sun',
    deity: 'Vishwedevas',
    symbol: 'Elephant tusk',
    gana: 'Manushya',
    sounds: ['Be', 'Bo', 'Ja', 'Ji'],
    description: 'The latter invincible one, associated with victory, leadership, and universal harmony. Connected to all the gods.',
  },
  Shravana: {
    number: 22,
    sanskrit: 'श्रवण',
    span: { start: 280, end: 293.333 },
    sign: 'Capricorn',
    ruler: 'Moon',
    deity: 'Vishnu',
    symbol: 'Ear',
    gana: 'Deva',
    sounds: ['Khi', 'Khu', 'Khe', 'Kho'],
    description: 'Hearing, associated with learning, teaching, and devotion to Vishnu. Represents the power of sound and knowledge.',
  },
  Dhanishta: {
    number: 23,
    sanskrit: 'धनिष्ठा',
    span: { start: 293.333, end: 306.667 },
    sign: 'Capricorn',
    ruler: 'Mars',
    deity: 'Vasu',
    symbol: 'Drum',
    gana: 'Rakshasa',
    sounds: ['Ga', 'Gi', 'Gu', 'Ge'],
    description: 'The wealthiest, associated with wealth, music, and prosperity. Connected to the eight Vasus.',
  },
  Shatabhisha: {
    number: 24,
    sanskrit: 'शतभिषा',
    span: { start: 306.667, end: 320 },
    sign: 'Aquarius',
    ruler: 'Rahu',
    deity: 'Varuna',
    symbol: 'Circle',
    gana: 'Rakshasa',
    sounds: ['Go', 'Sa', 'Si', 'Su'],
    description: 'A hundred physicians, associated with healing, mystery, and the ocean god. Connected to Varuna.',
  },
  'Purva Bhadrapada': {
    number: 25,
    sanskrit: 'पूर्वभाद्रपदा',
    span: { start: 320, end: 333.333 },
    sign: 'Aquarius',
    ruler: 'Jupiter',
    deity: 'Aja Ekapada',
    symbol: 'Sword',
    gana: 'Manushya',
    sounds: ['Se', 'So', 'Da', 'Di'],
    description: 'The former beautiful footed, associated with transformation, spiritual growth, and the one-footed goat.',
  },
  'Uttara Bhadrapada': {
    number: 26,
    sanskrit: 'उत्तरभाद्रपदा',
    span: { start: 333.333, end: 346.667 },
    sign: 'Pisces',
    ruler: 'Saturn',
    deity: 'Ahir Budhnya',
    symbol: 'Twins',
    gana: 'Manushya',
    sounds: ['Du', 'Jam', 'Jham', 'Khan'],
    description: 'The latter beautiful footed, associated with wisdom, spirituality, and the serpent of the depths.',
  },
  Revati: {
    number: 27,
    sanskrit: 'रेवती',
    span: { start: 346.667, end: 360 },
    sign: 'Pisces',
    ruler: 'Mercury',
    deity: 'Pushan',
    symbol: 'Fish',
    gana: 'Deva',
    sounds: ['De', 'Do', 'Cha', 'Chi'],
    description: 'The wealthy, associated with prosperity, guidance, and nourishment. Connected to the god who protects travelers.',
  },
}

export const NAKSHATRA_ORDER = [
  'Ashwini',
  'Bharani',
  'Krittika',
  'Rohini',
  'Mrigashira',
  'Ardra',
  'Punarvasu',
  'Pushya',
  'Ashlesha',
  'Magha',
  'Purva Phalguni',
  'Uttara Phalguni',
  'Hasta',
  'Chitra',
  'Swati',
  'Vishakha',
  'Anuradha',
  'Jyeshtha',
  'Mula',
  'Purva Ashadha',
  'Uttara Ashadha',
  'Shravana',
  'Dhanishta',
  'Shatabhisha',
  'Purva Bhadrapada',
  'Uttara Bhadrapada',
  'Revati',
]
